insert into properties (
  title, description, city, locality, rent, maintenance, deposit, brokerage, bhk, furnishing, parking,
  available_from, tenant_allowed, verification_status, availability_status, global_status, spaciousness_score,
  sunlight_score, maintenance_condition_score, pros, cons, missing_info, search_document, is_global_inventory
) values
('2BHK near Cyber City', 'Park-facing apartment on a higher floor with balcony and good ventilation.', 'Gurgaon', 'DLF Phase 2', 52000, 5000, '2 months', '15 days', '2BHK', 'semi-furnished', 'available', '2026-08-01', 'family', 'unverified', 'unknown', 'active', 7, 6, 7, array['near Cyber City','parking','good society'], array['maintenance extra'], array['carpet area','daytime video'], 'Title: 2BHK near Cyber City. City: Gurgaon. Locality: DLF Phase 2, near Cyber City. Rent: 52000. Maintenance: 5000. BHK: 2BHK. Furnishing: semi-furnished. Brokerage: 15 days. Parking: available.', true),
('Bright 2BHK in Sector 43', 'Well-maintained apartment close to metro with covered parking.', 'Gurgaon', 'Sector 43', 48000, 4000, '2 months', 'no brokerage', '2BHK', 'semi-furnished', 'covered parking', 'Immediate', 'family,couple', 'verified', 'unknown', 'active', 6, 7, 8, array['metro nearby','no brokerage','covered parking'], array['older society'], array['exact floor'], 'Title: Bright 2BHK in Sector 43. City: Gurgaon. Locality: Sector 43. Rent: 48000.', true),
('Premium 3BHK Golf Course Road', 'Large apartment in premium society with amenities.', 'Gurgaon', 'Golf Course Road', 78000, 9000, '2 months', '1 month', '3BHK', 'semi-furnished', 'available', '2026-08-15', 'family', 'unverified', 'unknown', 'active', 8, 6, 8, array['premium society','spacious'], array['above typical 2BHK budget','brokerage high'], array['brokerage confirmation'], 'Title: Premium 3BHK Golf Course Road. City: Gurgaon. Locality: Golf Course Road. Rent: 78000.', true),
('Compact 1BHK Cyber Hub side', 'Compact unit suited for single tenant.', 'Gurgaon', 'Cyber Hub', 36000, 2500, '1 month', '15 days', '1BHK', 'fully furnished', 'not confirmed', 'Immediate', 'bachelor', 'unverified', 'unknown', 'active', 4, 5, 6, array['near office hubs','fully furnished'], array['compact'], array['parking'], 'Title: Compact 1BHK Cyber Hub side. City: Gurgaon. Locality: Cyber Hub. Rent: 36000.', true),
('Family 2BHK in Noida Sector 75', 'Gated society flat with balcony and power backup.', 'Noida', 'Sector 75', 33000, 3500, '2 months', 'no brokerage', '2BHK', 'semi-furnished', 'available', '2026-08-01', 'family', 'verified', 'unknown', 'active', 7, 5, 7, array['gated society','power backup'], array['not Gurgaon'], array['sunlight video'], 'Title: Family 2BHK in Noida Sector 75. City: Noida. Locality: Sector 75. Rent: 33000.', true);
